package finanzas.domain;

import static finanzas.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class CuentaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCuentaAllPropertiesEquals(Cuenta expected, Cuenta actual) {
        assertCuentaAutoGeneratedPropertiesEquals(expected, actual);
        assertCuentaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCuentaAllUpdatablePropertiesEquals(Cuenta expected, Cuenta actual) {
        assertCuentaUpdatableFieldsEquals(expected, actual);
        assertCuentaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCuentaAutoGeneratedPropertiesEquals(Cuenta expected, Cuenta actual) {
        assertThat(actual)
            .as("Verify Cuenta auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCuentaUpdatableFieldsEquals(Cuenta expected, Cuenta actual) {
        assertThat(actual)
            .as("Verify Cuenta relevant properties")
            .satisfies(a -> assertThat(a.getNombre()).as("check nombre").isEqualTo(expected.getNombre()))
            .satisfies(a ->
                assertThat(a.getSaldoInicial())
                    .as("check saldoInicial")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getSaldoInicial())
            )
            .satisfies(a -> assertThat(a.getDescripcion()).as("check descripcion").isEqualTo(expected.getDescripcion()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCuentaUpdatableRelationshipsEquals(Cuenta expected, Cuenta actual) {
        // empty method
    }
}
