package finanzas.domain;

import static finanzas.domain.AssertUtils.bigDecimalCompareTo;
import static finanzas.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class MovimientoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMovimientoAllPropertiesEquals(Movimiento expected, Movimiento actual) {
        assertMovimientoAutoGeneratedPropertiesEquals(expected, actual);
        assertMovimientoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMovimientoAllUpdatablePropertiesEquals(Movimiento expected, Movimiento actual) {
        assertMovimientoUpdatableFieldsEquals(expected, actual);
        assertMovimientoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMovimientoAutoGeneratedPropertiesEquals(Movimiento expected, Movimiento actual) {
        assertThat(actual)
            .as("Verify Movimiento auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMovimientoUpdatableFieldsEquals(Movimiento expected, Movimiento actual) {
        assertThat(actual)
            .as("Verify Movimiento relevant properties")
            .satisfies(a -> assertThat(a.getTipo()).as("check tipo").isEqualTo(expected.getTipo()))
            .satisfies(a -> assertThat(a.getMonto()).as("check monto").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getMonto()))
            .satisfies(a ->
                assertThat(a.getFechaMovimiento())
                    .as("check fechaMovimiento")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(expected.getFechaMovimiento())
            )
            .satisfies(a ->
                assertThat(a.getFechaRegistro())
                    .as("check fechaRegistro")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(expected.getFechaRegistro())
            )
            .satisfies(a ->
                assertThat(a.getFechaActualizacion())
                    .as("check fechaActualizacion")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(expected.getFechaActualizacion())
            )
            .satisfies(a -> assertThat(a.getDescripcion()).as("check descripcion").isEqualTo(expected.getDescripcion()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMovimientoUpdatableRelationshipsEquals(Movimiento expected, Movimiento actual) {
        assertThat(actual)
            .as("Verify Movimiento relationships")
            .satisfies(a -> assertThat(a.getCategoria()).as("check categoria").isEqualTo(expected.getCategoria()))
            .satisfies(a -> assertThat(a.getCuenta()).as("check cuenta").isEqualTo(expected.getCuenta()));
    }
}
