package finanzas.domain;

import static finanzas.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class PresupuestoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPresupuestoAllPropertiesEquals(Presupuesto expected, Presupuesto actual) {
        assertPresupuestoAutoGeneratedPropertiesEquals(expected, actual);
        assertPresupuestoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPresupuestoAllUpdatablePropertiesEquals(Presupuesto expected, Presupuesto actual) {
        assertPresupuestoUpdatableFieldsEquals(expected, actual);
        assertPresupuestoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPresupuestoAutoGeneratedPropertiesEquals(Presupuesto expected, Presupuesto actual) {
        assertThat(actual)
            .as("Verify Presupuesto auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPresupuestoUpdatableFieldsEquals(Presupuesto expected, Presupuesto actual) {
        assertThat(actual)
            .as("Verify Presupuesto relevant properties")
            .satisfies(a -> assertThat(a.getMonto()).as("check monto").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getMonto()))
            .satisfies(a -> assertThat(a.getPeriodo()).as("check periodo").isEqualTo(expected.getPeriodo()))
            .satisfies(a -> assertThat(a.getFechaInicio()).as("check fechaInicio").isEqualTo(expected.getFechaInicio()))
            .satisfies(a -> assertThat(a.getFechaFin()).as("check fechaFin").isEqualTo(expected.getFechaFin()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPresupuestoUpdatableRelationshipsEquals(Presupuesto expected, Presupuesto actual) {
        assertThat(actual)
            .as("Verify Presupuesto relationships")
            .satisfies(a -> assertThat(a.getCategoria()).as("check categoria").isEqualTo(expected.getCategoria()));
    }
}
